sudo: required
dist: trusty

language: go

services:
  - docker

go:
  - 1.9

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - master
    - travis-testing

script:
  - ln -s $GOPATH/src/github.com/hashicorp/vault $GOPATH/src/github.com/Tim15/vault
  - make bootstrap
  - travis_wait 75 make test
  - travis_wait 75 make testrace
