sudo: required
dist: trusty

language: go

services:
  - docker

go:
  - 1.9

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - master
    - travis-testing

install:
  - git clone https://github.com/Tim15/vault $GOPATH/src/github.com/hashicorp/vault
  - cd $GOPATH/src/github.com/hashicorp/vault

script:
  - make bootstrap
  - travis_wait 75 make test
  - travis_wait 75 make testrace
