version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/hashicorp/vault
    steps:
      - checkout
      - setup_remote_docker
      # - run: git clone https://github.com/Tim15/vault $GOPATH/src/github.com/hashicorp/vault
      # - run: cd $GOPATH/src/github.com/hashicorp/vault
      - run: docker ps
      - run: docker run -d -p 80:80 --name web nginx
      - run: docker ps
      - run: curl 0.0.0.0:80
      - run: curl 127.0.0.1
      - run: sleep 1
      - run: curl 0.0.0.0:80
      - run: curl 127.0.0.1
      - run: docker stop web
      - run: docker ps
      - run: make bootstrap
      - run: make test
      - run: make testrace
